server.port=${PORT:8082}
spring.application.name=acceso-service

# MySQL
spring.datasource.url=${DB_ACCESO_URL:jdbc:mysql://localhost:3306/db_acceso?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:kidcare123}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT — mismo secret que los demas servicios
jwt.secret=${JWT_SECRET:kidcare-secret-key-2024-segura-32chars}
jwt.expiration=${JWT_EXPIRATION:86400000}

# URL del MS Historial (para retornar historial al medico en CU014)
historial.service.url=${HISTORIAL_SERVICE_URL:http://localhost:8084}
